name: Android CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - "**.gradle"
      - "**.rs"
      - "**/Cargo.toml"
      - ".github/workflows/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "**.gradle"
      - "**.rs"
      - "**/Cargo.toml"
      - ".github/workflows/**"
  release:
    types: [ created ]

permissions:
  contents: write
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: 'armv7-linux-androideabi,i686-linux-android,aarch64-linux-android,x86_64-linux-android'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: platform-tools build-tools;33.0.0 cmake;3.22.1 ndk;26.2.11394342
        env:
          SKIP_JDK_VERSION_CHECK: true
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew :module:zipRelease -Prelease
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: geoink-core-zip
          path: out/*.zip
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release' || github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: geoink-core-zip
          path: out/
      - name: Deploy to GitHub Releases
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        with:
          files: out/*.zip
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to GitHub Releases (Draft)
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          files: out/*.zip
          draft: true
          overwrite_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
